### ISSUE TITLE
随机传送建议

### ISSUE THREAD

**Issue by MinecraftFish** [EarthDLL/Unknown-Server-Framework#11]
在下界随机传送时，如果脚下是岩浆，就在脚下生成一个下界岩；在末地随机传送时，如果脚下是岩浆，就在脚下生成一个末地石

**Comment by EarthDLL** [comment]
但是实际上插件先把玩家传送到高空，在寻找落地方块位置，如果找不到落地方块的话，怎么确定这个落地石要放在哪？

**Comment by MinecraftFish** [comment]
在下界的话，可以在下方找的岩浆；末地的岛，高度都差不多，因此可以在一个固定的y轴放置

**Comment by EarthDLL** [comment]
这样的话不用打龙就能靠随机传送拿鞘翅了，不建议加这个
