### ISSUE TITLE
领地建议

### ISSUE THREAD

**Issue by MinecraftFish** [EarthDLL/Unknown-Server-Framework#23]
由于大量玩家不知道这个计分板怎么填，因此做出如下建议：
1.增加领地功能的开关
2.为“扣费积分板”增加默认值
3.若该积分板不存在，则自动创建

**Comment by EarthDLL** [comment]
1.开关一直都有
2.无论是否创建默认计分板，管理者都必须学会如何操作计分板，重点不在这里
我的解决方法是填完配置后检测计分板是否可用，不可用则弹窗提示
