### ISSUE TITLE
[日志功能][提案]领地访客记录警告

### ISSUE THREAD

**Issue by dyf189** [EarthDLL/Unknown-Server-Framework#40]
在[日志功能]中添加**警告**的log(关于[领地])
记录**领地访客**进入领地，方便当访客权限 _可以破坏、点火_ 时关于领地破坏的排查
类似于巡查日志

other:
也可以对TNT，点火等疑似破坏性行为添加到警告日志里

1. TNT、末影水晶和地狱、末地床
2. 火焰附加、火矢、打火石点火
3. 活塞、漏斗

**Comment by EarthDLL** [comment]
在领地内无法使用打火石、破坏方块的

**Comment by EarthDLL** [comment]
完成
