### ISSUE TITLE
优化初始化提示

### ISSUE THREAD

**Issue by MinecraftFish** [EarthDLL/Unknown-Server-Framework#49]
强烈要求在进入游戏的初始化提示里加入关于「若要在服务器内使用，请不要在单人游戏内初始化插件」的提示，防止有人不看文档 。同时，建议将初始化的文本“输入………获取最高op”改为“输入………初始化插件并获取最高op”，之前有人问怎么初始化。。。

**Comment by EarthDLL** [comment]
完成！
